version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: pip3 install -r requirements.txt && streamlit run app.py --server.port=8501 --server.address=0.0.0.0
